local level = {
    ambient="1.0,1.0,1.0",
    gravity="0.0,-9.8,0.0",
    entidades = {
        {
            name="Camera",
            id=0,
            components={
                transform={
                    position="0,3000,0",
                    rotation="-90,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                camera={
                    near="0.1",
                    far="5000",
                    autoaspect="true",
                    aspect="1.78",
                    fov="50",
                    proyection="1",
                    viewport="0,0,1,1",
                    color="0.2,0.2,0"
                }
            }
        },
        {
            name="Floor",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="25.0,1.0,25.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="Rojo",
                    visible="true"
                },
                collider={
                    type="box",
                    x="10.0",
                    y="1.0",
                    z="10.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall1",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="-1250,0.0,0",
                    rotation="0,0,0",
                    scale="1.0,5.0,25.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="Azul",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall2",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="1250,0.0,0",
                    rotation="0,0,0",
                    scale="1.0,5.0,25.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="Azul",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall3",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="0,0,1250",
                    rotation="0,0,0",
                    scale="25.0,5.0,1.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="Azul",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall4",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="0,0,-1250",
                    rotation="0,0,0",
                    scale="25.0,5.0,1.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="Azul",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Player",
            id=1,
            components={
                transform={
                    parent="-1",
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1.0,1.0,1.0"
                },
                mesh={
                    mesh="ninja.mesh",
                    material="",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="false",
                    density="1000"
                },
                personaje={
                    maxHealth="3",
                    lifefactor="0.05"
                },
                jugador={
                    speed="500"
                },
                lookatMouse={
                    test="false"
                },
				shoot={
					shootTime="500"
				}
            }
        },
        {
            name="SpanwZombies",
            id=0,
            components={
                transform={
                    parent="-1",
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1"
                },
                spawnZombis={
                    null="",
                }
            }
        }
    }
}

function GetLevel ()
  return level
end

function pruebaTexto()
    print('Im Working YESS')
end