local level = {
    ambient="1.0,1.0,1.0",
    gravity="0.0,-9.8,0.0",
    entidades = {
        {
            name="Camera",
            id=0,
            components={
                transform={
                    position="0,3000,0",
                    rotation="-90,0,0",
                    scale="1,1,1",
                    parent="-1"
                },
                camera={
                    near="0.1",
                    far="5000",
                    autoaspect="true",
                    aspect="1.78",
                    fov="50",
                    proyection="1",
                    viewport="0,0,1,1",
                    color="0.317,0.819,0.964"
                }
            }
        },
		{
            name="MainMusicPlayScene",
            id=6,
            components={
                audioSource={
					audioFileName="musicPlayScene.mp3",
					channel="0",
					loop="true",
					startOnPlay="true"
				}
            }
        }, 
        {
            name="Floor",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="25.0,1.0,25.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="Grass",
                    visible="true"
                },
                collider={
                    type="box",
                    x="10.0",
                    y="1.0",
                    z="10.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall1",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="-1250,0.0,0",
                    rotation="0,0,0",
                    scale="1.0,5.0,25.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="WallsL",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall2",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="1250,0.0,0",
                    rotation="0,0,0",
                    scale="1.0,5.0,25.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="WallsL",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall3",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="0,0,1250",
                    rotation="0,0,0",
                    scale="25.0,5.0,1.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="WallsL",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Wall4",
            id=2,
            components={
                transform={
                    parent="-1",
                    position="0,0,-1250",
                    rotation="0,0,0",
                    scale="25.0,5.0,1.0"
                },
                mesh={
                    mesh="cube.mesh",
                    material="WallsL",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="true"
                }
            }
        },
        {
            name="Player",
            id=1,
            components={
                transform={
                    parent="-1",
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1.0,1.0,1.0"
                },
                mesh={
                    mesh="ninja.mesh",
                    material="Player",
                    visible="true"
                },
                collider={
                    type="box",
                    x="1.0",
                    y="1.0",
                    z="1.0",
                    trigger="false"
                },
                rigidbody={
                    static="false",
                    density="1000"
                },
                personaje={
                    maxHealth="3",
                    lifefactor="0.05"
                },
                jugador={
                    speed="500"
                },
                lookatMouse={
                    test="false"
                },
				shoot={
					shootTime="500"
				},
				audioSource={
					audioFileName="walkingsound.mp3",
					channel="9",
					loop="false",
					startOnPlay="false"
				}
            }
        },
        {
			name="Heart1",
            id=1,
            components={
				image={
					positionX="0.01",
					positionY="0.05",
					nombrePanel="Heart1",
					material="Corazon",
					dimensionX="0.1",
					dimensionY="0.1"
				}
            }
        },
        {
			name="Heart2",
            id=1,
            components={
				image={
					positionX="0.01",
					positionY="0.15",
					nombrePanel="Heart2",
					material="Corazon",
					dimensionX="0.1",
					dimensionY="0.1"
				}
            }
        },
        {
			name="Heart3",
            id=1,
            components={
				image={
					positionX="0.01",
					positionY="0.25",
					nombrePanel="Heart3",
					material="Corazon",
					dimensionX="0.1",
					dimensionY="0.1"
				}
            }
        },
        {
            name="SpanwZombies",
            id=0,
            components={
                transform={
                    parent="-1",
                    position="0,0,0",
                    rotation="0,0,0",
                    scale="1,1,1"
                },
                spawnZombis={
                    newZombiesDelay="800",
                },
				audioSource={
					audioFileName="golpeado.mp3",
					channel="11",
					loop="false",
					startOnPlay="false"
				}
            }
        },
		{
			name="Score",
            id=10,
            components={
				scoreInGameText={
					positionX="0.913",
					positionY="0.8",
					texto="SCORE\n",
					nombreTexto="ScoreText",
					tamLetra="0.05",
					nombrePanel="ScorePanel",
					dimensionX="0.05",
					dimensionY="0.05",
					color="Black"
				}
            }
		},
		{
			name="Round",
            id=11,
            components={
				roundText={
					positionX="0.037",
					positionY="0.8",
					texto="ROUND\n",
					nombreTexto="RoundText",
					tamLetra="0.05",
					nombrePanel="RoundPanel",
					dimensionX="0.05",
					dimensionY="0.05",
					color="Black"
				}
            }
		},
        {
            name="Exit",
            id=2,
            components={
				exitOnPlay={
					positionX="0.88",
					positionY="0.00",
					texto="",
					nombrePanel="ExitPanel",
					nombreTexto="ExitTexto",
					tamLetra="0.05",
					material="ExitMaterial",
					dimensionX="0.12",
					dimensionY="0.06",
					type="CHANGE_SCENE",
					nextScene="EndScene.lua",
					clickDelay="300"
				},
				audioSource={
					audioFileName="click.mp3",
					channel="1",
					loop="false",
					startOnPlay="false"
				}
            }
        }
    }
}

function GetLevel ()
  return level
end

function pruebaTexto()
    print('Im Working YESS')
end